name: ScriptCraftPlugin
main: net.walterhiggins.scriptcraft.ScriptCraftPlugin
version: [[version]]
commands:
   js:
      description: Evaluate javascript.
      usage: /<command> Javascript code
      permission: ScriptCraftPlugin.evaluate
      permission-message: You don't have <permission> permission. This permission is only available to operators.
